feeds/pt.json

Soflusa is Lisbon's Ferry service

 pt: Add Soflusa

---

feeds/us.json

us: Add "fix" for Amtrak

---

feeds/us-ma.json

I found these transit agencies from Transitland's place listing for Massachusetts https://www.transit.land/places/United%20States%20of%20America/Massachusetts

More transit agencies in Massachusetts

---

feeds/us-oh.json

Add "fix": true for Miller transportation

Add fix miller transport

---

feeds/us-ia.json

Added the State of Iowa to the list to help fix issue #201

---

feeds/us-in.json

This is my first time contributing to Transitous and am having trouble navigating how to test the changes locally. Healthy skepticism is justified, but since the data is fetched from Transitland Atlas I'm hopeful this makes it more sound.

Add USA/Indiana/Indianapolis IndyGo realtime feed information

---

feeds/us-ar.json
feeds/us-ka.json

Add remaining feeds in Kansas from Transitland.

Move feed Little Rock to Arkasas

---

feeds/tr.json

Reverts public-transport/transitous#536

Revert "Izmir eshot fix"

---

feeds/us.json

Improve North American coverage status #201 by adding Brightline.

Add Brightline to us.json

---

feeds/pt.json

Fixes #503 and add new feed for Comboios de Portugal (CP) :)

Add Comboios de Portugal (CP) [PT] + skip broken feeds

---

feeds/mx.json

Improve Mexico coverage (#201)

Add Mexico

---

feeds/pt.json

Source, found the feed here: https://nap-portugal.imt-ip.pt/nap/multimodalsupply

Fix Metro Lisboa

---

website/content/_index.html

Fix KTrip link

---

feeds/nz.json

API key is mine, contact me for issues relating to it.
I'm not sure whether the api key is really necessary for the realtime feed, but it doesn't break when it does have it, so that's probably the safest bet for now.

feat(feeds): NZ.json - added Metro Christchurch w/ API key

---

src/fetch.py

This is useful for example for the hr-zet feed, which is often published before it is valid.

fetch: Don't use feed versions that are not yet valid

---

feeds/pr.json

Add Puerto Rico

---

feeds/us-ut.json

Add Utah [US]

---

feeds/us-wy.json

Add Wyoming [US]

---

feeds/us-nm.json

Add New Mexico [US]

---

feeds/us-tx.json

Add Texas [US]

---

feeds/us-wv.json

Add West Virginia [US]

---

feeds/us-fl.json

Add first Florida feeds [US]

---

feeds/us-az.json

Add Phoenix [Arizona, US]

---

feeds/us-mi.json

Improve Detroit area coverage [US]

---

website/static/custom.css

Make all icons visible, else Bimba is hidden without scrolling

website: Change to app grid

---

feeds/us-ak.json
website/hugo.toml

Add Alaska [US]

---

feeds/my.json

Fix ktmb [MY]

---

feeds/it.json

Fix it-Lazio-Cotral

---

feeds/us-pa.json

Improves #201 and #79 
I'm merging on main, because the feed limit seems to have been raised.

Improve Pennsylvania [US]

---

feeds/us-ca.json

Added entries for:
- Burbank Bus
- ~~Glendale Beeline~~
- Santa Clarita Transit
- AVTA
- Metrolink
this is my first PR so I may have made a mistake

Add more LA County bus and regional rail operators

---

feeds/us-fl.json

Fix us-fl.json

---

feeds/fi.json

Move away from gtfs.pro, this should improve #679 and fix #678.
The data comes from https://finap.fi/#/service/2790/4103, but I don't know it matches exactly the data that was available through gtfs.pro.

Update finferries [FI]

---

feeds/ca-qc.json

Skip STO (CA-QC)

---

feeds/gr.json

Ignore TLS error for TrainOSE [GR]

---

feeds/us-me.json

Add Maine, US-ME

---

feeds/us-nh.json

Add New Hampshire [US]

---

feeds/us-vt.json

Add Vermont [US]

---

feeds/cz.json

Skip DPLMJ [CZ]

---

feeds/us-tx.json

Fix corpus-christi [US-TX]

---

feeds/gb.json

Try updating feed url to fix #672, took the download urls provided on the busmaps webpage :)

Fix GB feeds

---

feeds/ca.json

Skip Cold-Lake-Transit & Fredericton-Transit [CA]

---

feeds/us-fl.json

Skip tri-rail [US-FL]

---

feeds/it.json

Fix it.json

---

feeds/us-in.json

Fix us-in.json

---

feeds/pl.json

Fix pl.json

---

feeds/us-il.json

Fix us-il.json

---

feeds/ca-on.json

Fix ca-on.json

---

feeds/es.json

See https://github.com/public-transport/transitous/issues/118#issuecomment-2568250975

Add GTFS-RT for Ferrocarriles-de-la-Generalitat-de-Cataluña [ES]

---

feeds/ca.json

Fix ca.json

---

feeds/us-wi.json

Add feeds for Wisconsin [US]

---

feeds/us-nv.json

Add Nevada [US]

---

feeds/us-va.json

Add Virginia [US]

---

feeds/us-ca.json

Fix us-ca.json

---

feeds/id.json

Fix id.json

---

feeds/it.json

Add more datasources for Tuscany. Fixes #849

---

feeds/pr.json

Fix Puerto Rico

---

docs/README.md
docs/docs/index.md
feeds/ie.json
src/fetch.py
src/metadata.py
src/mobilitydatabase.py
src/transitland.py

Contributes to https://github.com/public-transport/transitous/issues/903

Implement initial support for the Mobility Database

---

feeds/fi.json

Work around expired SSL certificate

---

feeds/ca-qc.json

Add Bixi Montreal

---

feeds/us-wa.json

us-wa: Add skip for Appleline-Goldline-Dungenessline-Grapeline

---

feeds/lu.json
src/region_helpers.py

This one is almost Austria-level over-engineering, but this solution works

Add new source for Luxembourg

---

src/fetch.py

Could interfere with gtfs-rt matching

fetch: Don't merge identical routes

---

src/fetch.py

This allows to check cases in which the feed is not well-formed before
gtfsclean, for example because the relevant files are in a subdirectory.
It also reduces the number of special cases our own parsing code needs
to handle well, like leading whitespace.

Check validity after gtfsclean processing

---

feeds/cz.json
src/mobilitydatabase.py
src/transitland.py

Adding Pilsen and it's public transport to cz.json (based on https://github.com/transitland/transitland-atlas/pull/1470)

Add PMDP to cz.json

---

docs/docs/index.md
feeds/at.json
src/fetch.py
src/generate-austria.py
src/metadata.py

https://github.com/public-transport/gtfsclean/pull/10

Support route display name copy option from gtfsclean

---

feeds/fr.json

I never really understood how to handle issues and there are enough other maintainers now.

Step down as fr maintainer

---

feeds/us-ca.json

This resolves https://github.com/public-transport/transitous/issues/1050

Url override for OC Bus in California

---

feeds/gb.json

Fix gb.json

---

feeds/om.json

Fix om.json

---

feeds/us-oh.json

Fix us-oh.json

---

feeds/pl.json

My first pull request ever, hope it's fine

Change ZKM Gdynia data source to Transitland

---

feeds/pl.json

- Add RT for Warsaw Public Transport
- Add Warszawska Kolej Dojazdowa
- Add Koleje Śląskie and Łódzka Kolej Aglomeracyjna

Update feeds for Poland

---

feeds/de.json

Adding some German carsharing providers and especially some from Baden-Württemberg. I tested the setup locally and the server starts without any issues. Also in my tests they got picked up for routing, although I did not test all individual providers.

Add some German carsharing providers

---

feeds/in-ts.json

* Add region for Telangana (India)
* Add feed for hyderabad metro

Add feed for Hyderabad Metro

---

feeds/in-ka.json

* Add region for Karnataka (India)
* Add feed for BMTC

Add feed for BMTC

---

ansible/hosts
ansible/motis-staging.yml
ansible/roles/motis-staging/files/motis-update-feeds.service
ansible/roles/motis-staging/files/motis-update-feeds.sh
ansible/roles/motis-staging/files/motis-update-feeds.timer
ansible/roles/motis-staging/files/motis.service
ansible/roles/motis-staging/tasks/main.yml
ansible/roles/motis/tasks/main.yml
ansible/roles/nginx/files/nginx.conf
ansible/roles/nginx/tasks/main.yml
ansible/roles/nginx/templates/transitous.conf.j2

Hi, I added an ansible playbook to set up a staging instance of motis. Comments welcome :D

add an ansible role to set up a staging instance

---

feeds/ro.json

Added both static & real-time sources for Iasi
Added real-time source for Cluj

Support for Iasi & Cluj support update

---

feeds/ro.json

- List cleaned up and ordered alphabetically, all feeds now start with capital letters
- Moved most feeds over from http to their existing mobility db entries
- Oradea static feed added

Multiple updates for ro.json

---

feeds/au.json

Add Adelaide Metro (AU)

---

feeds/fr.json
src/generate-france.py

Update generate-france.py to support GBFS feeds + regenerate FR

---

website/content/_index.html
website/content/api.html
website/hugo.toml
website/layouts/shortcodes/library-card.html

website: Add library section

---

website/content/api.html

As discussed in public-transport/transitous#1144

Revert "Add python client to libraries"

---

feeds/pl.json

Add one feed to pl.json

---

feeds/cz.json

Add realtime gtfs and up to date timetables directly from operator

Update cz.json IDSJMK realtime

---

feeds/pl.json

I've finally found the PKS Poznań feed link and also updated more licenses and added more feeds provided by @izgirlcat (thanks!)
(I swear at some point I'll tidy the file, so feeds are there alphabetically)

Poland further license updates and new feeds

---

feeds/it.json

Not much to say, however the gtfs lacks shapes.txt

added Calabria (italy)  data from mobility database

---

feeds/us-az.json

Adding GTFS feed for mountain line busses in Flagstaff, Arizona, USA.
https://www.transit.land/feeds/f-mountain~line~az

Add feed for US AZ Mountainline Buses

---

feeds/us-az.json

Adding GTFS feed for Sun Tran light rail in Tucson, Arizona, USA.
https://www.transit.land/feeds/f-9t9-suntran

Add feed for US AZ Sun Tran Lightrail

---

feeds/it.json

Found here:
https://www.amts.ct.it/open-data

Add IT/Catania AMTS GTFS data (static feed)

---

website/content/api.html

add JS libs, more generic API links

---

feeds/pl.json

Adds a new community maintained feed in Warsaw metro area. Thanks to @luigi22 for creating this feed.

Add Mińsk Mazowiecki feed

---

src/fetch.py

Provides better error messages and a somewhat useful help output.

Use proper argument parsing in fetch.py

---

src/generate-motis-config.py

Gives us better error handling and help messages.
For further improvements here (like defaulting to full mode) we will need to move away from using consecutive positional arguments though, which will require breaking changes. So that's a separate change.

Use proper command line argument parsing in generate-motis-config.py

---

feeds/si.json

They added a few new ones in the meantime that I requested access for. They also added proper license documentation that I copied here.

Update feeds from the Slovenian NAP

---

feeds/be.json
feeds/ca-bc.json
feeds/ca-qc.json
feeds/nz.json
feeds/pl.json
feeds/us-ca.json
feeds/us-dc.json
feeds/us-de.json
feeds/us-fl.json
feeds/us-in.json
feeds/us-ks.json
feeds/us-md.json
feeds/us-mi.json
feeds/us-mo.json
feeds/us-nh.json
feeds/us-nm.json
feeds/us-nv.json
feeds/us-ny.json
feeds/us-or.json
feeds/us-tx.json
feeds/us-va.json
feeds/us-vt.json
feeds/us-wa.json
feeds/us-wy.json
src/generate-motis-config.py
src/metadata.py
src/transitland.py

Improve how transitous deals with transitland feeds that require authorization

---

docs/docs/index.md

Taken from https://volkerkrause.eu/2025/06/14/transitous-adding-data.html.
The information about diagnostics from there probably also makes sense here, but I'd put this into its own section below.

Add a section in the documentation about the used data types

---

feeds/pl.json

- Add RT feed for PKS Poznań
- Add RT feed for Kombus
- Add Środa Wielkopolska

Add RT Feeds from Goeuropa (Kombus, Środa, PKS Poznań)

---

feeds/pl.json

Actually found the last remaining feed from zbiorkom.live And also Skarżysko-Kamienna has appeared

Update pl.json feeds

---

website/.gitignore
website/content/_index.html
website/content/api.html
website/content/suppliers.html

As discussed during the hack weekend and thus especially looking for feedback from those of you who couldn't attend.

Add usage policy

---

feeds/nz.json

nz: fix headers yet again

---

feeds/gb.json
website/content/sources-great-britain.md

This one has more details, and should be updated quicker than the one we currently use
**CC**: @MrKrisKrisu, @HerrLevin, this might need changes in your license allowlist, and would probably cause complaints if it breaks.

gb: Switch to aubin gtfs feed

---

feeds/nz.json

nz: fix Metro Christchurch feeds

---

src/transitland.py

Old address can stay online for a while if needed, but the new deployment is easier for me to manage, so I'd like to move to that one :)

Update proxy to new address

---

feeds/au-vic.json
feeds/au.json

cc @g1nger-bred, this PR can supersede #1438
This PR adds all the missing Victoria static and realtime data, and moves them to their own file just so they don't overcrowd the main Australia feed

au: Victoria refactor

---

feeds/si.json

Fix si.json

---

feeds/hr.json

Fix #1251 
cc @vekejsn I don't know if this issue could be fixed upstream instead?

Fix hr.json

---

feeds/ba.json
feeds/hr.json
feeds/rs.json

Should fix #1537 #1538 #1556 with a permanent URL for feeds.

Update feed URL's for ba,hr,rs

---

ansible/roles/motis/files/motis.service
ansible/roles/motis/templates/motis-update-feeds-secondary.sh
ansible/roles/motis/templates/motis-update-feeds.service

`#WantedBy=multi-user.target`
in order to avoid running this on boot

update motis-update-feeds (lua scripts, robustness)
