public-transport/transitous

.github/workflows/reuse.yml, .gitignore, .gitmodules, .reuse/dep5, LICENSES/AGPL-3.0-or-later.txt, LICENSES/CC0-1.0.txt, README.md
@JBBgameich We also need to define a license for the feed data files. We can do that globally with any license we want (I just picked CC0 as we happen to have that already anyway), or we can also license them individually if we expect different licenses there going forward. I have no strong preference either way, the approach taken here is mainly motivated by quickly getting to something compliant for testing the CI check.
=> Add REUSE compliance check, and make things actually compliant

feeds/ca-bc.json
Fix #252
This is caused by these two lines in calendar_dates.txt:
```
20240526,c_21151_b_31125_d_127t_5603137_b_31125_tn_0,,2
20240526,c_21151_b_31125_d_127t_5603137_b_31125_tn_0,,1
```
where the same service was listed as being both removed (2) and added (1) for the specific date
=> Fix BC-Ferries

feeds/fr.json
I added a feed for Brittany public transport. It aggregates the feeds of each city in Brittany in a single one. There are some errors (12 stops and 828 stop times, most of them for train stop times, which is already included in SNCF TER feed) so I added the "fix" attribute.
=> Add feed for Brittany (train, bus, metro, car, boat)

feeds/it.json
Added Movibus, AirPullman, NET, STAR and STAV from https://www.agenziatpl.it/open-data/gtfs
I suppose those data must be checked regularly as the filename contains a date and they may change the date when updating the data.
=> Added some autobus companies in Lombardy

feeds/hu.json
Their GTFS feed isn't downloadable anymore.
Fixes #439.
=> Remove v-busz for now

feeds/us-pa.json, src/fetch.py
Add SEPTA (Southeastern Pennsylvania Transportation Agency) for Philadelphia area.
=> Initial feeds for Pennsylvania

src/generate-attribution.py, website/data/license.json, website/layouts/shortcodes/source-table.html
I think we should also include the sources/licenses of the (GTFS-)RT feeds, since occasionally the license differs from the static feed (e.g. for Germany).
Surely one could come up with something more sophisticated that only displays this information if it is different from the static feed; I opted to just add a sentence below the `Original file` and `Processed file` buttons of the respective static feed. But I'm open for suggestions :)
(Also, this lead to some refactoring, which is why the diff is so large...)
=> Include rt sources in credits list

feeds/it.json
Improve Italian coverage #114.
Important feeds in Italy are still missing (Frecciarossa, Italo, Itabus for example).
=> Add Cotral (Lazio, IT)

feeds/nz.json
Thanks to whoever added Baybus to Transitland!
This should be the last of the larger cities, all the others don't have publicly available GTFS feeds as far as I can tell, so some emailing will be in order for the future.
=> feat(feeds): NZ.json - added BUSIT and Baybus

feeds/us-ca.json
timepoint value in stop_times.txt is invalid (value should be 1 or 0 but is instead 10)
this should probably be emailed to the agency using the templates, making this pr to fix import
=> Add fix flag to capital corridor

feeds/us-ca.json
Added gtfs-rt feeds for burbank bus, avta, and santa clarita transit as they seem to have rt feeds available without api keys
Changed skip reason on Glendale beeline to add text about compression mentioned in an earlier review
=> Add gtfs-rt feeds, fix skip reason on glendale beeline

feeds/hu.json
Adds some major Hungarian cities' operators.
The original source for SZKT is http://szegedimenetrend.hu/google_transit.zip
=> Add new operators to hu

feeds/us.json
https://catenarymaps.org Our research group supplies GTFS rt for amtrak that's converted from the website
https://birch.catenarymaps.org/gtfs_rt?feed_id=f-amtrak~rt&feed_type=vehicle
https://birch.catenarymaps.org/gtfs_rt?feed_id=f-amtrak~rt&feed_type=trip
Readable versions here:
https://birch.catenarymaps.org/gtfs_rt?feed_id=f-amtrak~rt&feed_type=vehicle&format=json
https://birch.catenarymaps.org/gtfs_rt?feed_id=f-amtrak~rt&feed_type=trip&format=json
What the dataset looks like:
=> Amtrak shapes no longer broken, use Catenary Map's GTFS RT converter

ci/fetch-feeds.py
I haven't tested this on the real transitous repo yet, but this should maybe improve the raised issues by linking to the feed file directly.
However, with the current setup the commit hash doesn't get updated if the issue gets updated afaik.
=> Improve transitous bot

feeds/fr.json, src/generate-france.py
Improve handling of multiple feeds (GTFS, GTFS-RT) in one dataset, this fixes #692 .
=> France: improve handling of multiple feeds in one dataset

feeds/eu.json, feeds/fr.json, src/generate-france.py
Changes:
- Regenerate FR
- Use up to date **Eurostar** GTFS generated in `fr.json`
- Remove **Thalys** from `eu.json`, but for now keep the up to date Thalys GTFS + GTFS-RT from `fr.json` (because it has better shapes and RT).
Improves #748
=> Improve Eurostar/Thalys + regenerate FR

feeds/nz.json
There isn't a transitland entry for this yet, so adding it by URL for the moment.
=> feat(feeds): NZ.json - added Horizons Regional Council via URL

feeds/pl.json
Tested with GNOME Maps 47.3 by running with the `MOTIS_BASE_URL=http://localhost:8080` environment variable.
-- 
Just as an aside, the steps at https://transitous.org/doc/#running-a-transitous-instance-locally seems somewhat outdated (mainly there's config.yml instead of config.ini, and `motis -c config.ini --server.host 0.0.0.0 --server.static_path /opt/motis/web` did not seem to work but running `motis server` did). I used .woodpecker/data-import.yml as a guide and somehow managed to get through
=> pl: Add Szczecin feed

feeds/nz.json
No realtime info is available, but the standard GTFS is under CC-BY 4.0.
=> feat(feeds): NZ.json - added license info to Horizons Regional Council

feeds/us-wa.json
This adds all of the feeds for transit authorities for washington state that exist on transitland which are listed here: https://mrsc.org/explore-topics/government-organization/special-districts/local-transit-authorities
This includes some missing GTFS-RT feeds which were previously missing
This also fixes the indentation of the file, as some of it was previously indented with either 4 or 5 spaces at different parts of the file.
Improves #201
=> Add feeds for Washington state [US] transit authorities

feeds/pl.json
Hello! 👋
`ZTM TransportGZM` is a public transport organization based in the Silesian Voivodeship, Poland. They manage buses, trams, trolleybuses and bikes. 
ZTM is the organization that governs it, "[TransportGZM](https://transportgzm.pl)" is a brand under which they run busses/trams/trolleybuses, and brand "[TransportGZM MetroRower](https://metrorower.transportgzm.pl/)" is for bikes (actually NextBike runs it :wink:).
This PR adds ZTM TransportGZM GTFS and GTFS-RT.
- The GTFS-RT has a static URL. Licensed under CC-BY-4.0
- Transport GZM has two versions of GTFS ["normal"](https://otwartedane.metropoliagzm.pl/en/dataset/rozklady-jazdy-gtfs-wersja-tymczasowa) and ["extended"](https://otwartedane.metropoliagzm.pl/en/dataset/rozklady-jazdy-i-lokalizacja-przystankow-gtfs-wersja-rozszerzona). …
=> Add PL Silesian buses (Transport GZM)

motis/config.yml
As discussed in #857, increasing the timeout for RT downloads, since this timeout does seem to encompass the entire transfer and not only until the first packet.
(Haven't actually tested it by emulating a slow connection, but quite confident that this should improve things and not make anything else worse :)
=> Increase rt feed download timeout

src/generate-motis-config.py
When testing locally e.g. a specific country, one first generates a config file full of feeds, just to remove them. This change allows to specify a certain feeds.json, to only fill the feeds of a specified country in the config.yml
So when I want to setup a local instance with only german feeds, I can generate the config as following
```shell
python ./src/generate-motis-config.py full de
```
Let me know what you think
=> Allow to specify a feed for generation

feeds/il.json
I've sent a message to Busofash regarding their error in the GTFS file.
=> Add initial Israel sources

docs/docs/index.md
Make sure to ignore the robots.txt, otherwise the command does not work.
resolves #932
=> Fix download command in documentation

feeds/ro.json, src/metadata.py, src/mobilitydatabase.py
I added an escape hatch to not use the mirrored version from Mobility Database, because sometimes they are blocked as well.
I'm not entirely happy about the different semantics of proxy for transitland and use-origin, but neither do I want to turn proxy on unconditionally nor loose the advantage of the mobilitydatabase cache.
=> Add more feeds in Romania

docs/docs/index.md, feeds/de.json, motis/config.yml, src/generate-motis-config.py, src/metadata.py, src/transitland.py
This PR adds initial GBFS support as discussed in #74 
For now it only supports GBFS feeds from the transitland atlas and generates a working config.
However, for this specific feed I need to double check why it does not show up in search results, so do not merge for now.
=> Initial GBFS support

website/content/_index.html, website/content/api.html
This PR [refers to a request](https://github.com/public-transport/transitous/issues/947) to add references/links to talks and presentations about Transitous.
The exact wording is still debatable, so I am open for any suggestion.
The result looks like this:
=> Issue-947: Add references to conference talks to api page

website/content/_index.html
Uses an unordered list to display several references, instead of buttons. Resolves GH-947
=> Use unordered list element for references

src/generate-motis-config.py
Needed e.g. for the API key of the Finnish national aggregate feed.
=> Support custom HTTP headers for GBFS as well

feeds/fi.json
The linked website mentions a deprecation of the current feed URL and wants users to migrate to the new one.
=> Update Finish feed to new Source

docs/docs/index.md, feeds/lu.json
Small step to implement  #1029 (support of GBFS feeds of `url` type was already there, just not documented it seems).
=> GBFS feeds with url type + update docs

motis/config.yml, website/content/sources.html
Adds link to https://transitous.org/sources/ in the UI and as a response header of every API call (this needs not-yet-released motis 2.0.49, but shouldn't break anything rn). Adds attribution to OSM to the sources page.
=> Improve attribution

feeds/pl.json
- Added Koleje Wielkopolskie
- Cleanup Łódzka Kolej Aglomeracyjna and Koleje Śląskie (followup from #1082)
- Pull transitland-atlas to latest version (required for other changes)
=> Add koleje wielkopolskie and cleanup pl

feeds/pl.json, src/transitland.py
**Why?**
PKP-Intercity feed has international trains ending at last station in Poland. Trains from Poland to Berlin are in the gtfs.de DB feed (but are not in the main german DELFI feed). It feels like a quick fix can be made, to have data for those trains.
Similar issue exists on trains for example from Poland to Czechia, but at the moment transitous has data for those trains in Czechia and uggests a transfer between them (while not ideal, no data is missing).
**How?**
Use `f-germany~long~distance~rail` (gtfs.de long distance feed) with all agencies but PKP Intercity filtered out.
This will cause only small duplication (double the PL-DE trains on Polish side), but will allow to navigate on full routes and on route parts inside Germany.
Small change was required to make …
=> Add GTFS.de feed with Poland-Germany trains

feeds/pl.json
What?
Support Berlin - Warsaw/Kraków/Gdansk/Przemyśl trains in trainsitous
Why?
#1083 didn't help as it was supposed to. I missed the fact gtfs.de contains those trains in two parts: Berlin - Rzepin (operated by DB) and Rzepin - Warsaw (operated by PKP), therefore adding gtfs.de feed with all but PKP Intercity agencies filtered out resulted in just polish parts of those trains. I double checked and I couldn't find the german part of the trains anywhere else (DELFI feed, PKP Intercity feed, VBB feed).
How?
Add a custom feed based on gtfs.de, but only with the Berlin - Poland trains. Feed is generated daily by a script: https://github.com/kasmar00/gtfs-pkp-de. In the near future I plan to merge those split journeys into one (probably based on data from regular PKP Intercity feed, but that …
=> Custom PKP DE feed for Berlin - Poland trains

feeds/cz.json
Recently, I asked lead maintainer of CZPTT feed on their jrutil GitLab repo about the license and while the answer wasn't as conclusive as I'd like it to be _(if only the ministry of transport had a proper license attached to source data)_, I believe the response goes give more than enough reason to make this a CC0.
https://gitlab.com/dvdkon/jrutil/-/issues/13#note_2469249024
=> Update license for CZPTT feed in cz.json

feeds/de.json
Note: Ridedott is currently not available in the transitland-atlas, therefore it is added as URL type. See also https://github.com/transitland/transitland-atlas/issues/1538
=> Add Bikesharing providers from Frankfurt and Mainz

feeds/de.json
This PR adds Transitland Feeds for Nextbike Cities Dresden, Leipzig and Halle. 🚴
=> Add Nextbike GBFS for Dresden, Leipzig and Halle

website/content/_index.html
Like [discussed](https://github.com/public-transport/transitous/pull/1130#issuecomment-2868705710) in #1130, I've now set up a proper support/product page for my App Transportflow. I've updated the links in the App Store to not point to transitous.org and would like to link the product page in transitous as well.
=> Update Transportflow App Website

feeds/lt.json
Ironically Visi Maršrutai doesn't have all the routes, I've checked the Panėvežys area and found out the suburban lines were missing. So I've decided to add the B-Bus company group feed again, but this time in the proper country.
=> Bring back B-Bus feed

feeds/kr.json
[KR] Add nationwide GTFS feed for South Korea #1154
The feed was added to feeds/kr.json.
=> Add GTFS feed for South Korea

feeds/pl.json
Adds a custom created feed for Warsaw Tourist Lines that are not included in main Warsaw feed - ferries
=> Add Warsaw Ferry to pl.json

docs/docs/index.md, feeds/ch.json, src/fetch.py, src/generate-motis-config.py
This is almost identical to static GTFS feeds, the only reason we need it to be a different type is that gtfsclean can't handle Flex feeds, so we need to skip that in post-processing.
Also, add the Swiss GTFS-Flex feed so we have something to test with.
=> Add GTFS-Flex support

src/fetch.py
We need this e.g. for the `cars_allowed` field for ferries and car transport trains. It will also help with preserving Fares v2 related fields, although that needs more work to also preserve unknown files.
=> Keep additional GTFS fields that gtfsclean doesn't know about

feeds/ca-on.json
I have amended the `ca-on.json` feed in two ways:
1) For the GTFS `.zip` file to be directly downloaded from OCTranspo's dedicated server.  to directly link to OC Transpo's official URL.
2) For the GTFS-RT data to be pulled from a proxy set up by JBB on the Transitous matrix channel, which obscures the secret API key necessary to download the data. The API key has been registered under my name and email address according to official processes and rules spelled out by [OCTranspo](https://www.octranspo.com/en/plan-your-trip/travel-tools/developers/dev-doc).
=> Ottawa's OCTranspo changed to direct feed

feeds/ae.json
The feed is downloaded from Dubai Pulse portal and processed in Gitlab
=> Add Dubai feed

README.md, website/hugo.toml
Also needed to verify the Transitous Mastodon account.
=> Add Mastodon link

feeds/fi.json
That insists on an Accept-Encoding header set to gzip now, for transferring a zip-compressed file...
Fixes #1255
=> Fix retrieving the Finish Digitraffic GTFS file

docs/docs/index.md
Snapshot 4 lacks the GTFS Flex support for example.
=> Link to latest gtfsclean release

feeds/de.json
I think it's good enough to switch to the matched SIRI feeds (updated every 5 minutes only). This also still includes the data from the DELFI GTFS-RT Feed (updated every minute).
Not adding Service Alerts for the time being due to https://github.com/mfdz/GTFS-Issues/issues/189.
=> DE: Using the DELFI SIRI feeds

feeds/nl.json, src/fetch.py, src/metadata.py
Change the datasource from OVApi to OpenOV to solve issue #1347 and #1366.
With this change, the stoparea's are not longer available in the dataset. 
Issue #1366 will be solved because without the stoparea's, every stop with the same name will return their departures instead of just the one that is selected. 
Issue #1347 will also be solved because without the stoparea's, every stop will only return their departures and not the departures of locations on the other side of the country.
=> Update nl.json to solve #1347 and #1366

src/generate-attribution.py, website/layouts/shortcodes/source-table.html
With the new sorting the empty subdivisions come first, which the previous code didn't handle properly.
Also, sort feed names case-insensitively.
=> Fix grouping of subdivisions

feeds/nz.json
the feeds I fixed in #1409 still don't work because I forgot to add the `spec: gtfs-rt` key into the JSON
=> nz: add spec for RT feeds

feeds/sk.json
https://github.com/xhyrom/transiq/commit/f1fe7d7e0d0915d08b306805fd7ebe40c3d8263d
Use my own mirror as the data source. This allows me to build a scraper for other companies and potentially replace this source if it becomes restricted, as has happened with others.
The current data comes from [TransData](https://www.transdata.sk/), the company behind [Ubian](https://ubian.sk/). I also found [gtfs.transdata.sk](https://gtfs.transdata.sk), where some of this data is accessible without authorization.
=> sk: add SAD Prievidza

feeds/cy.json
So I figured the gtfs-rt for cyprus but it seems the static is broken now, it doesn't include any stops or stop_times, it seems two days ago it was still fine
=> cy realtime

feeds/ba.json, feeds/hr.json, feeds/rs.json, feeds/si.json
Fixes:
- Mostar GTFS URL
Changes:
- Srbijavoz GTFS to different merged source between OeBB HAFAS & w3.srbvoz.rs
- IJPP GTFS to use a processed version, that is more user friendly
- Liburnija Zadar GTFS-RT source
Adds:
- HŽPP GTFS-RT
- Split GTFS-RT
- Sisak GTFS-RT
- IJPP GTFS-RT
- Maribor GTFS & GTFS-RT
- Celje GTFS & GTFS-RT
- Srbijavoz GTFS-RT
=> Update ba.json, hr.json, rs.json & si.json

feeds/hr.json, feeds/si.json
- Adds trip updates and service alerts for LPP. Closes #651 
- Adds trip updates for Autotrolej and removes NAP feed (duplicate and outdated compared to other feed).
=> Add RT for LPP (SI) and Autotrolej (HR)

feeds/nz.json
self explanatory, fixes the naming of the Flamingo feeds so that all of them actually show up
=> nz: fix Flamingo naming

feeds/bg.json
Source: https://www.sofiatraffic.bg/en/info-center/gtfs-danni
Links are available in the Bulgarian version of the page https://www.sofiatraffic.bg/bg/info-center/gtfs-danni
=> bg: Replace Sofia GTFS feed with newly published official data

feeds/cz.json
I've added the CC0 license to JDF merged feed (same reason and license as for CZPTT) and removed Bean Shuttle, as it does not hold a license for regular lines and also destinations and origin points are in fact not fixed... it's just a shuttle minibus!
=> Add license for JDF merged and remove Bean Shuttle

feeds/gb.json
=> Remove Flixbus from gb-great-britain

feeds/us-wa.json
The [transitland-atlas feed for King County Metro](https://www.transit.land/feeds/f-c23-metrokingcounty) points to the Sound Transit API which requires a Sound Transit API key, but King County Metro publishes real-time feeds independently, and these are included in the mobilitydatabase.org dataset. The static feed for KCM has been updated in tandem with the real-time feeds to prevent potential compatibility issues.
In addition to publishing schedules for its own vehicles, Sound Transit [consolidates feeds](Consolidated GTFS Schedule File Set) for the entire Seattle metro area, so if there are trips in other agencies included in `f-c23-metrokingcounty` that aren't in `mdb-1330` it is, in principle, possible that Transitous will lose coverage for those trips. There's also …
=> Update King County Metro to MobilityDatabase feed, adding RT support

feeds/rs.json
Adds feeds for Litas, Autoprevoz Čačak, Kavim Jedinstvo and Pantransport.
=> Add unofficial intercity feeds for Serbia

feeds/pl.json
Sadly, for now the line 500 in PKS Nova will be duplicated due to lack of real time for the rest of the main feed
=> Add new Polish feeds

feeds/no.json
Since it's already present in eu.json
(with shapes and RT updates).
Closes #1548
=> no: Drop FlixBus from Entur feed

feeds/pl.json
Zbiorkom.live acts as a cache, not as publisher (something similar to how https://api.transitous.org/gtfs/ works), and may not have the most current feed versions.
(Also, this unifies the approach to feeds available via both zbiorkm.live and girlc.at, as some feeds had this double url, and some didn't).
=> Treat files.girlc.at as main urls

feeds/ch.json, scripts/ch-opentransportdataswiss.lua
Unlike the domestic trips, those don't have good route short names.
=> Improve display names for international trips in the Swiss feed

feeds/se.json, scripts/se-Trafiklab.lua
- Re-write route_type for tourist railways
- Add route_short_name on some routes only having long names, which actually have short names (numbers) in real life
- Map route colors for a few agencies/routes
=> Add script for Trafiklab

feeds/pl.json, scripts/pl-Koleje-Mazowieckie.lua, scripts/pl-PKP-Intercity.lua, scripts/pl-PKP-SKM.lua, scripts/pl-PolRegio.lua, scripts/pl-RegioJet.lua, scripts/pl-SKM-Warszawa.lua
Scripts for polish trains:
- PKP Intercity:
- differentiate clasz(High speed for EIP, Long distance for other), rail replacement bus
- better display name, in format `IC 1234 Train Name`, `EIP 1245` etc.
- Koleje Mazowieckie: differentiate clasz (Regio Express as Regional fast, regio as regional), rail replacement bus
- PKP SKM: route name (`S1`) and correct clasz (~Sbahn)
- Polregio: differentiate clasz (Regio as regional, InterRegio as Regional Fast), rail replacement bus
- RegioJet: differentiate clasz (Night route as night, other as as Long Distance), as mentioned in https://github.com/public-transport/transitous/pull/1498#issuecomment-3314778637 (cc: @Lach-anonym)
- SKM Warszawa: correct clasz (~Sbahn)
=> Add scripts for Polish trains

feeds/de.json
We have a dedicated feed for Eurostar that has shapes, colors and at least partial realtime data.
=> Drop Eurostar services from the DELFI feed

feeds/eg.json
Hey,
I found this website [[1](https://data.transportforcairo.com/#/)] which publishes several GTFS datasets, some of which (the two for Cairo that I included) are updated frequently [[2](https://data.transportforcairo.com/#/)].
From what I read ([[3](https://data.transportforcairo.com/about/)] "Each dataset in the system can be shared publicly or restricted to allow access to only specific users."), there should not be a problem of using this dataset here.
The other datasets are outdated, hence i did not include them.
=> Egypt - Cairo

scripts/de-DELFI.lua
What this doesn't cover yet are trips that are modeled as split trips with two different operators.
=> Fix display names on most of the international trips in the DELFI feed

feeds/at.json, src/generate-austria.py
Those were previously explicitly skipped in the generation script, from a time when we couldn't handle Flex yet.
=> Add Austrian GTFS Flex feeds

scripts/pl-RegioJet.lua
Fixing the route selector, as `"display-name-options": "copy-trip-names-matching"` creates extra route objects (one per each trip)
=> Fix RegioJet script

feeds/au-nsw.json, feeds/au.json, src/generate-australia-new-south-wales.py
cc @daviewales, you might be interested in this
This PR adds the Flex and RT data available from Transport for New South Wales (TfNSW). There are a few things that are suboptimal right now, so for now this is a draft.
The realtime feeds are paired with their *own* static feed which isn't compatible with the 'complete' feed that we currently have, so we pull a lookup table [they provide](https://opendata.transport.nsw.gov.au/data/dataset/reference-tables-tfnsw-gtfs-feeds) and add all the affected agency names into the feed file.
The other problem is that some of the timetables have a finer scope than the RT endpoints, which means Transitous would be redundantly pulling the same endpoints multiple times and thus using up more requests on my API key than we actually need. For example, there …
=> au: NSW feed refactor
